### ISSUE TITLE
Select item programmatically

### ISSUE THREAD

**Issue by spacedema** [iGenius-Srl/IGColorPicker#2]
Hi!

Thanks for the lib. How can I select item programmatically? 
colorPickerView.preselectedIndex = newValue didn't worked for me

Thanks

**Comment by andreaantonioni** [comment]
Paste here your code to setup the color picker ;)

**Comment by spacedema** [comment]
`class SomeViewController: UIViewController, ColorPickerViewDelegate, ColorPickerViewDelegateFlowLayout {

@IBOutlet weak var colorPickerView: ColorPickerView!
@IBOutlet weak var someButton: UIButton!

override func viewDidLoad() {
        super.viewDidLoad()
        colorPickerView.delegate = self
        colorPickerView.layoutDelegate = self
        colorPickerView.colors = colors
        colorPickerView.style = ColorPickerViewStyle.circle
        colorPickerView.selectionStyle = ColorPickerViewSelectStyle.check
	colorPickerView.preselectedIndex = 1 // works as expected, item is checked
}

@IBAction func somButtonClicked(_ sender: Any) {
// How can I select item via code?
        colorPickerView.preselectedIndex = 2 // Item not checked
    }

...
}`

**Comment by andreaantonioni** [comment]
`preselectedIndex` is a property thought to be used before the presentation of the color picker.

At the moment there's no way to select a color programmatically, it's a feature that I didn't think about. I'll try to implement it in the next few hour. In the meanwhile you may fork the project, implement this feature and send me a pull request 👍🏻

**Comment by spacedema** [comment]
I think I couldn't do it cause I'm new in swift :)

**Comment by andreaantonioni** [comment]
As you can see I've found time to work on your features 😅

**Comment by spacedema** [comment]
Did it  yesterday myself in fork but thank you anyway :)
