### ISSUE TITLE
Pod not found

### ISSUE THREAD

**Issue by sigmundfridge** [iGenius-Srl/IGColorPicker#4]
I've added the line 
`pod 'IGColorPicker'`
to my podfile, but I get 
`[!] Unable to find a specification for IGColorPicker`

Similarly 
```
$ pod search "IGColorPicker"
[!] Unable to find a pod with name, author, summary, or description matching `IGColorPicker`

```

**Comment by andreaantonioni** [comment]
```
$ pod search "IGColorPicker"

-> IGColorPicker (0.2.1)
   A customizable color picker for iOS in Swift
   pod 'IGColorPicker', '~> 0.2.1'
   - Homepage: https://github.com/iGenius-Srl/IGColorPicker
   - Source:   https://github.com/iGenius-Srl/IGColorPicker.git
   - Versions: 0.2.1, 0.2.0 [master repo]
```
Maybe try to update `Cocoapods` to `v. 1.2.0`

**Comment by sigmundfridge** [comment]
$ pod --version
1.2.1
$ pod search IGColorPicker
[!] Unable to find a pod with name, author, summary, or description matching `IGColorPicker`

**Comment by andreaantonioni** [comment]
I've tried the same on `1.2.1` and it works.

Try this: http://stackoverflow.com/questions/42764066/pod-search-xxx-and-return-unable-to-find
Otherwise I suggest you to uninstall and reinstall cocoapods

**Comment by sigmundfridge** [comment]
Actually, I had it working on one machine after updating. However, I've just gone back to that machine after a few days and it's back to not finding it again. It's still not working on my other machine (so that's two different setups). I'll try the instructions above and let you know

**Comment by sigmundfridge** [comment]
That fixed it. Strange that the same issue occurred on two separate machines at the same time but could be something to do with updating Cocoa pods. Thanks for the help
